apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: docu-chat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meet-bariya/docu-chat-config
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: docu-chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - createNamespace=true
